POST https://localhost:5000/createuser
Content-Type: application/json

{
   "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOiIxMjMiLCJpYXQiOjE3MDUxNTI3NTN9.wVkBix22HvY7LgVOqkyuOS-2-YG9WD2l7cbxknbl7k8"
}

##########

POST https://localhost:5000/payment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpYXQiOjE3MDU4NTc4MDMsImV4cCI6MTcwNTk0NDIwM30.X7tV-dQYVQJDLVwkDPBVB_mtmNX5DqByx5XlCUOMIJA

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjMsImRhdGUiOiIyMDI0LTEtMjIgMDoyNjo1NiIsImlkb3JkZXIiOm51bGwsImFtb3VudCI6MzAwMDAsImlhdCI6MTcwNTg1ODAxNiwiZXhwIjoxNzA1OTQ0NDE2fQ.7iAES0OyvWGqlgdp3GDm7WndqxqyTaXBhkuzeVXPBWs"
}



##########
POST https://localhost:5000/historypayment
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJpYXQiOjE3MDU4NTc4MDMsImV4cCI6MTcwNTk0NDIwM30.X7tV-dQYVQJDLVwkDPBVB_mtmNX5DqByx5XlCUOMIJA

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjMsImlhdCI6MTcwNTkzNzI1MCwiZXhwIjoxNzA2MDIzNjUwfQ.cepQMIOUKd7BcpDolsh_esCd_Mc4QFtXaB95MdaNdBM"
}