POST https://localhost:5000/createuser
Content-Type: application/json

{
   "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOiIxMjMiLCJpYXQiOjE3MDUxNTI3NTN9.wVkBix22HvY7LgVOqkyuOS-2-YG9WD2l7cbxknbl7k8"
}

##########

POST https://localhost:5000/payment
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEyMywiZGF0ZSI6IjIwMjQtMDEtMTMiLCJpZG9yZGVyIjoxLCJhbW91bnQiOjE1MDAwMCwiaWF0IjoxNzA1NTcxMzc2fQ.Jg8ewIWNUvqt2AnE1E1ZfXEGBNNrr7KQ3hrxcD2CfRg"
}



##########
POST https://localhost:5000/historypayment
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzZXIiOjEyMywiaWF0IjoxNzA1NTcxNzk1fQ.TCDByvaTFyJjuT0CnQyIQUTKeCpD1kGV6_oNzWD0eOM"
}